---
title: "Plano de Ensino"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Conteúdos

1. R e Rstudio

    - história
    - Quem é quem
    - Como buscar ajuda
    - Recursos disponíveis

2. instalação (workflows)

    - CRAN R
    - Rstudio
    - MikteX
    - Rtools
    - git

2.  R

    - arquivos `.R`, `.Rmd`, `.RDS` e `.RDA`, `.RDATA`
    - packages
        - CRAN, Bioconductor, **github**
    - o que é possível fazer
        - shiny
        - pdf
        - html

3.  Rstudio

    + navegação/Panes
        - editor, console, Environment, files, Plots, Viewer, Packages, help
    + Configuração
    + projetos
    + autocompletar
    + snippets
    + addins
    + atalhos

4. Introdução R

    + Buscando ajuda
        + help `?`, F1
        + rstudio community https://community.rstudio.com/
        + Curso-R https://discourse.curso-r.com/
        + google/stackoverflow
        + #Rstats
    + Comentário `#`
    + tipos atômicos (vetores):
        + números (inteiros e double)
        + texto (character)
        + lógicos
        + NA e NULL
        + ? fatores e datas
    + variáveis/nomes
    + operadores
        + atribuição
            + `<-`, `->`, `<<-`, `=`
        + aritmétricos
            + `+`, `-`, `*`, `/`, `^`
            + `%%`, `%/%`
            + `%*%`
        + Lógicos
            + vetorizados `&` e `|`
            + scalar `&&` e `||`
        + comparação
            + `==`, `!=`, `<`, `<=`, `>`, `>=`
        + sequencia (`:`)
            + `seq()`
            + pi:6 # real
            + 6:pi # integer
        + Pipe
            + `%>%` / `|>`
        + namespace
            + `::`, `:::`
    + funções
    + vetores
    + listas
    + data.frame/tibble
    + usando pacotes `library`
    + `names()`, `str()`
    
1. style guide

1. tarefas comuns

    1. Lendo
        + xlsx
        + txt
        + csv
        + BIG
        + ACCESS
        + `.RDA`
    1. Escrevendo
        + xlsx
        + csv
        + `.RDA`
        + ACCESS
    1. Criar/alterar colunas - dplyr
    1. Relatório
        + knitr/rmarkdown
        + markdown

5. tidyverse

    + base R x tidyverse
    + tidydata
    + tibble
    + tidyselect
        + `select`
        + `everything`
        + `all_of`/`any_of`
        + `starts_with`/`ends_with`/`contains`
        + `where`
        + operators (`:`, `!`, `c()`, `-`)
    + dplyr
        + head/tail
        + filter/slice
        + `mutate`
        + `summarise`
        + `group_by`
        + `across`
        + `count`
        + `case_when`
    + tidyr
        + pivot
        + separate
        + extract
    + grammar of graphics (ggplot)
        + aesthetics
            + y,x
            + color/fill
            + size
        + geoms
            + geom_line
            + geom_bar/col/histogram
            + geom_point/jitter
        + scales
            + continuos/discrete
        + themes
            + title/subtitle/caption
            + axis
            + 
    + outros
        + stringr
        + lubridate
        + forcats

1. base R

    + subseting

1. Funções

    + escopo

1. Controle de fluxo

    + loop
        + lapply, sapply, vapply
        + purrr::map_*
        + for, while
    + condicionais
        + `ifelse`, `case_when`
        + `if`
    + erro
        + `stop`
        
# atalhos

    + executar código
        + comando/seleção `ctrl+enter`
        + 

# conteúdos sem definição de onde devem ser apresentados

    + Rstudio snipets


    + Introdução ao git
    
        + o que é o git
        + branch
        + merge
        + remote
